services:
  - type: web
    name: soulsync-api-dev
    branch: dev
    env: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NODE_ENV
        value: dev
      - key: PORT
        value: 10000
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_PRESET
        value: soulsync_images
      - key: MAX_IMAGE_SIZE_KB
        value: "500"
      - key: FIREBASE_PROJECT_ID
        value: soulsync-b29c8
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://soulsync-dev-admin.web.app,https://soulsync-dev-host.web.app,https://soulsync-dev-quiz.web.app,https://soulsync-b29c8.web.app,https://soulsync-b29c8.firebaseapp.com,https://soulsync-prod-app.web.app,https://soulsync-prod-app.firebaseapp.com,http://localhost:5000,http://localhost:5001,http://localhost:5002
